package com.leisuretimedock.blasttravelreborn.content.menu;

import com.leisuretimedock.blasttravelreborn.BlastTravelReborn;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.inventory.MenuType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class BTRMenuTypes {
    public static final DeferredRegister<MenuType<?>> MENU_TYPES = DeferredRegister.create(ForgeRegistries.MENU_TYPES, BlastTravelReborn.MOD_ID);
    public static final RegistryObject<MenuType<CannonContainerMenu>> CANNON_CONTAINER_MENU =
            MENU_TYPES.register(
                        "cannon_container_menu",
                        () -> new MenuType<>(CannonContainerMenu::new, FeatureFlags.VANILLA_SET)
            );
    public static void register(IEventBus eventBus) {
        MENU_TYPES.register(eventBus);
    }
}
