package com.leisuretimedock.blasttravelreborn.content.entity;

import com.leisuretimedock.blasttravelreborn.BlastTravelReborn;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class BTREntityTypes {
    public static final DeferredRegister<EntityType<?>> ENTITY_TYPES = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, BlastTravelReborn.MOD_ID);
    public static final RegistryObject<EntityType<CannonEntity>> CANNON_ENTITY =
            ENTITY_TYPES.register(
                    "cannon",
                    () ->   EntityType.Builder.<CannonEntity>of(CannonEntity::new, MobCategory.MISC)
                            .sized(1, 0.8f)
                            .build((BlastTravelReborn.id("cannon")).toString()
            ));
    public static void register(IEventBus eventBus) {
        ENTITY_TYPES.register(eventBus);
    }
}
