package com.leisuretimedock.blasttravelreborn;

import com.leisuretimedock.blasttravelreborn.content.BTRParticleTypes;
import com.leisuretimedock.blasttravelreborn.content.entity.BTREntityTypes;
import com.leisuretimedock.blasttravelreborn.content.item.BTRItems;
import com.leisuretimedock.blasttravelreborn.content.menu.BTRMenuTypes;
import com.leisuretimedock.blasttravelreborn.network.BTRNetwork;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

@Mod(value = BlastTravelReborn.MOD_ID)
public class BlastTravelReborn {
	public static final String MOD_ID = "blasttravelreborn";
	public BlastTravelReborn() {
		FMLJavaModLoadingContext fmlJavaModLoadingContext = FMLJavaModLoadingContext.get();
		IEventBus modEventBus = fmlJavaModLoadingContext.getModEventBus();
		BTRNetwork.register();
		BTRItems.register(modEventBus);
		BTRParticleTypes.register(modEventBus);
		BTREntityTypes.register(modEventBus);
		BTRMenuTypes.register(modEventBus);
	}

	public static ResourceLocation id(String path) {
		return new ResourceLocation(MOD_ID, path);
	}

	public static ResourceLocation id(String mod_id, String path) {
		return new ResourceLocation(mod_id, path);
	}
}
