package com.leisuretimedock.blasttravelreborn.content.item;

import com.leisuretimedock.blasttravelreborn.BlastTravelReborn;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = BlastTravelReborn.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ItemEventHandler {
    @SubscribeEvent
    public static void onCreativeEvent(BuildCreativeModeTabContentsEvent event) {
        if (event.getTabKey() == CreativeModeTabs.FUNCTIONAL_BLOCKS)
            event.accept(BTRItems.CANNON_ITEM);
    }
}
