package com.leisuretimedock.blasttravelreborn.datagen.provider;

import com.leisuretimedock.blasttravelreborn.BlastTravelReborn;
import com.leisuretimedock.blasttravelreborn.content.BTRParticleTypes;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.common.data.ParticleDescriptionProvider;

import java.util.ArrayList;
import java.util.List;

public class BTRParticleProvider extends ParticleDescriptionProvider {

    public BTRParticleProvider(PackOutput output, ExistingFileHelper fileHelper) {
        super(output, fileHelper);
    }

    @Override
    protected void addDescriptions() {
        List<ResourceLocation> cannonBlastTextures = new ArrayList<>();
        for (int i = 0; i <= 7; i++){
            cannonBlastTextures.add(BlastTravelReborn.id("blast_smoke_" + i));
        }
        spriteSet(BTRParticleTypes.CANNON_BLAST.get(), cannonBlastTextures);
    }
}
