package com.leisuretimedock.blasttravelreborn.content;

import com.leisuretimedock.blasttravelreborn.BlastTravelReborn;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class BTRParticleTypes {
    public static final DeferredRegister<ParticleType<?>> PARTICLE_TYPES = DeferredRegister.create(ForgeRegistries.PARTICLE_TYPES, BlastTravelReborn.MOD_ID);
    public static final RegistryObject<SimpleParticleType> CANNON_BLAST =
            PARTICLE_TYPES.register(
                    "cannon_blast",
                    () -> new SimpleParticleType(true)
            );
    public static void register(IEventBus eventBus) {
        PARTICLE_TYPES.register(eventBus);
    }
}
